#ifndef SHAREDLIBRARYSAMPLE_EXPORT_H__
#define SHAREDLIBRARYSAMPLE_EXPORT_H__

#ifdef _WIN32
#define SHAREDLIBRARYSAMPLE_EXPORT_SYMBOL __declspec(dllexport)
#define SHAREDLIBRARYSAMPLE_IMPORT_SYMBOL __declspec(dllimport)
#else
#define SHAREDLIBRARYSAMPLE_EXPORT_SYMBOL
#define SHAREDLIBRARYSAMPLE_IMPORT_SYMBOL
#endif

#ifdef SharedLibrarySample_EXPORTS
#	define SHAREDLIBRARYSAMPLE_API SHAREDLIBRARYSAMPLE_EXPORT_SYMBOL
#else
#	define SHAREDLIBRARYSAMPLE_API SHAREDLIBRARYSAMPLE_IMPORT_SYMBOL
#endif

#endif // SHAREDLIBRARYSAMPLE_EXPORT_H__
